### ISSUE TITLE
Fedora 35 build

### ISSUE THREAD

**Issue by ispanos** [jahnf/Projecteur#177]
Hello, and thanks for your time on this. I am using fedora 35 and the build for 34 works, but wouldn't it be better to get a release for fedora 35?

**Comment by jahnf** [comment]
Yes, it would. That said supporting all the different Linux distributions that I don't even use is a little tedious :)

**Comment by ispanos** [comment]
Can I help? I would need some guidance, because I haven't packaged a program before, but I could help.

**Comment by jahnf** [comment]
Oh sure, I am no package expert either, I went with CPack since I am already using CMake.

The it is currently set up via builds within a GitHub action and a docker container for each target distro

It would definitely help if you could 
1.  Verify that the package built on fedora 35 works. You can produce that package with `make dist-package` after you set up the build successfully (see readme) - this is possible just on the host system.

Other than that if you create a docker build container similar to the one for fedora 34 (not much work if nothing major changes) - verify that the build works inside that container...

But even 1. is already a great help 👍

**Comment by jahnf** [comment]
Edit: I looked into flatpak, snap and others a while back and decided against it - (there is a closed issue that discusses it) - it was mainly because of the installation of a udev rule file if I remember correctly. 

Maybe those have advanced also. I am happy to consider it again if it is feasible.

**Comment by jahnf** [comment]
automated build for fedora 37 is available (and soon also fedora 38)
