### ISSUE TITLE
Update the zoom regularly

### ISSUE THREAD

**Issue by mayanksuman** [jahnf/Projecteur#40]
When user is using zoom spotlight and he switches window using `Alt+TAB`, the zoom from the last screen is shown even if the screen has changed.

**Comment by jahnf** [comment]
True, but as it was already discussed in #28 - There is no way around this with Qt features - or at least not that I know of. Since we have to take a screenshot before the spot is shown.
While the spot is shown there is no way to get the current screen without including the spot itself.
You will see the same effect if you have a video running for example.

Marking this as wontfix - but keeping it open, so other can find this information more easily.

**Comment by mayanksuman** [comment]
I am working on solution and have got some success. Probably, will be able to submit a pull request soon.

**Comment by jahnf** [comment]
I guess as a Gnome tool it probably has access to the window manager and compositor. Which is of course a possibility - but what about KDE, and all the other Linux desktops?
I think for a small presentation tool the current implementation is sufficient.

**Comment by BriggsyUK1970** [comment]
BTW I have downloaded 6.35 to test the zoom on OpenSUSE 15.1 KDE and it works a treat (zoom keeps pace with LibreOffice slides ;0) Thanks so much!

**Comment by jahnf** [comment]
> BTW I have downloaded 6.35 to test the zoom on OpenSUSE 15.1 KDE and it works a treat (zoom keeps pace with LibreOffice slides ;0) Thanks so much!

Thanks for the feedback, great to hear :wink: :tada:
