### ISSUE TITLE
Add settings to commands

### ISSUE THREAD

**Issue by mlouielu** [jahnf/Projecteur#44]
Hi there, first of all, thanks for this project, its awesome!

I'm using KDEConnect-android + KDEConnect, which provide a simple spotlight function in it. I've made a modification in [KDEConnect](https://github.com/mlouielu/kdeconnect-kde) to make it use Projecteur as the spotlight backend, which use `projecteur -c spot=on/off` to toggle the spotlight function.

It is nice to have all the settings can pass by the commands `-c`, so it is possible for others to config at runtime, I'll provide a prototype PR for this.

How do you folks think?

**Comment by jahnf** [comment]
Thanks, I guess settings via command options would make _Projecteur_ more usable in combination with scripts. I'll have a look at the PR tomorrow.

**Comment by jahnf** [comment]
I wasn't aware of the presenter functionality in KDE Connect, interesting. 
Also I left some comments in #45 - let me know what you think.

**Comment by jahnf** [comment]
Setting of values is now available from the command line (not yet shown in the help - next commit...)
But the issue with zoom still remains. If the zoom gets activated while the spot is active - no screenshot can be taken - so either there is an outdated screen image or no screen image (if the zoom never was activated since start of projecteur)

**Comment by mlouielu** [comment]
Nice works! Thanks for the commit!
