### ISSUE TITLE
Mate System tray

### ISSUE THREAD

**Issue by guntherwagenhofer** [jahnf/Projecteur#8]
Thanks a lot for the devlopment of the software.
You are my hero.
I think I have the most done. By moving or turning the pointer I can move the cursor on the screen (so I think the udev rules are set correctly). But there is one problem left. I'm using Ubuntu 18.10 with mate. In my system tray there is no icon and I can't find the tool to change the preferences.
It would be nice if you have an idea to solve this problem.

Thanks a lot.

Gunther

**Comment by jahnf** [comment]
Good morning. Thanks for notifying about the issue. I noticed also on KDE Plasma that the system tray was there but without an actual icon. It could be either that the SVG format is not supported for system tray icons or that Mate and KDE don't like something else about that SVG icon I created (I used Inkscape for it).

So if you replace the icon in the resource file as well as the reference to it in the code it might work. I might be able to try it, but I do not have too much access to my usual (development) environment the next 2 weeks or so.

**Comment by jahnf** [comment]
Had the chance to do a quick update for the icon. Please give it a try with the latest changes on develop.

**Comment by guntherwagenhofer** [comment]
Thanks a lot for the fast work. Unfortunately it doesn't work yet.

Greetings


_________________________
Gunther Wagenhofer
Hohenlohe 1
93176 Beratzhausen
gunther.wagenhofer@gmx.de

Am 18.03.19 um 07:18 schrieb Jahn F.:

**Comment by jahnf** [comment]
It works for me in a Ubuntu 18.10 Mate Virtual Machine.
Built today from latest develop with compiler/Qt/cmake from the Ubuntu repository. See screenshots.
I had to install a couple of qtquick qml modules from the repository otherwise the application will complain and not start for missing modules.
If this does not help you, please post the cmake and build command lines and output and also the outputput of `git --describe`, so it's easier to see what your setup is.

![ubuntu18 10 run](https://user-images.githubusercontent.com/5852240/54524054-36bd0480-4971-11e9-909d-fbd35e1daa2b.png)
![Screenshot from 2019-03-18 11-27-23](https://user-images.githubusercontent.com/5852240/54524058-391f5e80-4971-11e9-85fb-1f7b7f11e1a1.png)

**Comment by guntherwagenhofer** [comment]
Now it works for me, too. Thanks a  lot for your help. My first try with 
Qt5 from the ubuntu-repositories was not successful. So I tried it with 
the Repository from the Qt-Project. The installation did run with the 
problem, that the icon didn't appear in the systray. After your hint 
with the ubuntu-repositories I deinstalled the Qt 5 in /opt and 
installed it again from ubuntu. After the instatllation of the qtquick 
qml modules I installed packages which included the missing files etc. 
Than I ran the installation in order of your description an it works now.


Thanks a lot for your help and for the development of this gimmick!!. It 
is very nice.

Gunther

_________________________
Gunther Wagenhofer
Hohenlohe 1
93176 Beratzhausen
gunther.wagenhofer@gmx.de

Am 18.03.19 um 11:37 schrieb Jahn F.:
