### ISSUE TITLE
Feature Request: Multi-Screen Overlay

### ISSUE THREAD

**Issue by maehne** [jahnf/Projecteur#80]
**Is your feature request related to a problem? Please describe.**

In issue #76, I tested Projecteur's multiscreen support. Currently, only one screen gets dimmed if the spotlight gets activated. This is in many cases desirable, e.g., when using the spotlight function in a presentation with a tool providing a presenter console (e.g., [pdfpc](https://pdfpc.github.io/)). However, it might in other occasions also be desirable that all screens get dimmed when the spotlight is active, e.g., when demonstrating some complex program, which manages multiples windows distributed across several screens.

**Describe the solution you'd like**

For the latter use case, I think it would be beneficial to add an option to the Projecteur GUI that if enabled would cause all screens to be dimmed (see my [idea in issue #76](https://github.com/jahnf/Projecteur/issues/76#issuecomment-633223842)).

@jahnf [reacted to this idea](https://github.com/jahnf/Projecteur/issues/76#issuecomment-633225805):
> Good idea :+1:, might be possible - it would involve multiple overlay windows though (one per screen). I'll remember to try that at some point.

For the smoothest user experience, partial spotlights would be shown on two screens if the spotlight approaches the screen borders. Though, spotlight shapes might not fully match in size if the scaling / resolution / size of the screens differs.

However, I wonder if multiple windows are necessary to implement this feature. At least on KDE Plasma, a window can be resized to cover seamlessly multiple screens.

**Describe alternatives you've considered**

I don't see other alternative at the moment.

**Comment by jahnf** [comment]
> However, I wonder if multiple windows are necessary to implement this feature. At least on KDE Plasma, a window can be resized to cover seamlessly multiple screens.

Yes this needs some investigation. But it must also be considered that screens can not only be ordered side-by-side and each screen can have quiet different screen resolutions. Additionally - currently the spotlight size is currently a percentage of the screen resolution height.

**Comment by mrshu** [comment]
Hello everyone,

Would you have any pointers as to where to start with something like this? Having Projecteur on just one screen is pretty tough for me and so I'd like to help with that if possible.

Thanks!

**Comment by jahnf** [comment]
Hi Marek
great that you like to contribute.
I'll try to put together some hints and pointers for you tomorrow, so that you could start on a feature branch.
Do you have (some) experience with Qt and C++?

**Comment by jahnf** [comment]
Alright, so here are some thoughts - don't know if they will help you :smile: - but anyway: 
* Currently the one overlay window that exists follows the mouse cursor across screens, so when the mouse cursor moves from one screen to another, the window is moved to that other screen (with a lot of trickery to make it always full screen -  found by trial and error to make it work on different Desktop environments) / see `projecteurapp.cc`
* At first I would start at is a little concept, where
  * you would make sure that you have a good idea on how to manage multiple overlay windows (that should use the same QmlEngine) and also make sure that this also works when somebody plugs in an additional screen or removes one.
  * (I don't think one overlay stretching across all screens will work, since different screens will have different resolutions and also can be arranged in all kind of different ways) - but then again, maybe you can proof me wrong
  * It's also good to keep in mind that this would be an option that can be turned of, so it should still be possible to have the current one overlay window behavior when that features is disabled in the options.
* If you managed to manage multiple overlay windows, then it needs to be ensured that only one "spot" is shown where the mouse is currently - I haven't thought about it too much, but that can be solved - but the main work I think is in the overlay window management, which needs to react to screen changes.

**Comment by jahnf** [comment]
FYI, I started working on this feature - hopefully I can soon provide a version to check out on the related feature branch.

**Comment by jahnf** [comment]
@maehne @mrshu When you have time you can test the early version of the multi-screen overlay,
so that issues with might come with different setups can be tackled.

Known issues in this current version on the `feature/multi-screen-overlay` branch:
* zoom does not work yet with multi-screen-overlay
* the 'highlight spot' is currently shown on all screens

**Comment by mrshu** [comment]
Hi @jahnf,

I only got to trying this out now, when you merged it in. I tested the `0.9-alpha.64` version on Fedora 31 (I got it from https://bintray.com/jahnf/Projecteur/projecteur-develop/0.9-alpha.64#files/packages/branches/develop/0.9-alpha.64). Note that I ran Gnome on X server.

After clicking on `Enable multi-screen overlay`, everything worked as I'd expect it to -- even zoom -- on all of the attached screens. I did not test adding/removing screens and geometry changes but I am happy to, if that would be valuable.

Thanks again for investing time into this -- `Projecteur` will be a standard part of my talk-giving setup from now on.

**Comment by jahnf** [comment]
@mrshu - great to hear!
I don't expect any hiccups on adding/removing screens or resolution changes - but then again, you never know, so it would be great if you can test it on your setup.

And as an unrelated question: Does the bash auto completion work on your Fedora? I added it a few weeks ago to the packages but only really tested it on Ubuntu :grinning:

**Comment by mrshu** [comment]
> Does the bash auto completion work on your Fedora?
I tested it out now and it works out of the box.

Nicely done!
